aedat4_folder: /files/aedat4/ #relative to script
bag_folder: /files/bags/ #relative to script
bag_name: ''
cam_info_topic: /dvs/camera_info
image_topic: /dvs/image/raw
events_topic: /dvs/events
imu_topic: /dvs/imu

conversion_type: 0 #only 0 implemented for now -> timestamp based

reset_timestamp: 3.5 #ms

